import type {
  DeliveryOrder,
  OrderStatus,
  Rider,
  RiderStatus,
  VehicleType,
} from "./types";

/* ---------- helpers ---------- */

let orderSeq = 1;

const makeOrder = (
  customer: string,
  address: string,
  zone: string,
  amount: number,
  itemCount: number,
  status: OrderStatus,
  estimatedTime: string,
): DeliveryOrder => ({
  id: `del-ord-${orderSeq}`,
  orderNumber: orderSeq++,
  customer,
  address,
  zone,
  amount,
  itemCount,
  status,
  estimatedTime,
});

const makeRider = (
  id: number,
  name: string,
  phone: string,
  vehicleType: VehicleType,
  plateNumber: string,
  status: RiderStatus,
  zone: string,
  totalDelivered: number,
  dutyTime: string,
  activeOrders: DeliveryOrder[],
): Rider => ({
  id,
  name,
  phone,
  vehicleType,
  plateNumber,
  status,
  zone,
  totalDelivered,
  dutyTime,
  activeOrders,
});

/* ---------- mock data ---------- */

export const INITIAL_RIDERS: Rider[] = [
  makeRider(
    1,
    "Omnia Maher",
    "01987654321",
    "Motorcycle",
    "ABCD 1234",
    "On-Route",
    "Kafr Abdo",
    18,
    "4h 25mins",
    [
      makeOrder(
        "Ahmed El-Sayed",
        "23, إبراهيم راضي, Abo Al Nwateer, alex",
        "Kafr Abdo",
        170.40,
        2,
        "On The Way",
        "15 min",
      ),
      makeOrder(
        "Omar Khaled",
        "89, محمد الفتوح, Giza, cairo",
        "Kafr Abdo",
        85.00,
        1,
        "Assigned",
        "8 min",
      ),
    ],
  ),
  makeRider(
    2,
    "Omnia Maher",
    "01987654321",
    "Car",
    "XYZ 5678",
    "On-Route",
    "Gleem",
    14,
    "32 mins",
    [
      makeOrder(
        "Layla Ibrahim",
        "9 Corniche El-Nil, Gleem, Alexandria",
        "Gleem",
        145.00,
        3,
        "Preparing",
        "12 min",
      ),
      makeOrder(
        "Nour Hossam",
        "33 Port Said St, Gleem, Alexandria",
        "Gleem",
        210.50,
        2,
        "On The Way",
        "18 min",
      ),
    ],
  ),
  makeRider(
    3,
    "James Miller",
    "02987654321",
    "Motorcycle",
    "LMN 2345",
    "Active",
    "Semouha",
    22,
    "12 mins",
    [],
  ),
  makeRider(
    4,
    "Alice Lee",
    "03987654321",
    "Van",
    "QRS 6789",
    "On-Route",
    "Roushdy",
    31,
    "2h 35mins",
    [
      makeOrder(
        "Sara Nabil",
        "7 Mostafa Kamel St, Kafr Abdo, Alexandria",
        "Roushdy",
        320.75,
        2,
        "Preparing",
        "20 min",
      ),
      makeOrder(
        "Mohamed Fathy",
        "5 El-Nasr Road, Semouha, Alexandria",
        "Roushdy",
        195.00,
        1,
        "Assigned",
        "25 min",
      ),
      makeOrder(
        "Tarek Samir",
        "12 Ahmed Orabi St, Sporting, Alexandria",
        "Roushdy",
        115.00,
        3,
        "Order Placed",
        "30 min",
      ),
    ],
  ),
];
