import type {
  CustomerLookup,
  DeliveryZone,
  Driver,
  Order,
  OrderCategory,
  OrderSource,
  OrdersSummary,
  OrderStatus,
  ProductOption,
} from "./types";

export const ORDER_STATUS_OPTIONS: OrderStatus[] = [
  "Pending",
  "Confirmed",
  "Preparing",
  "On The Way",
  "Delivered",
  "Cancelled",
];

export const ORDER_CATEGORY_OPTIONS: OrderCategory[] = [
  "All Categories",
  "Sandwiches",
  "Coffee",
  "Bakery",
  "Meals",
];

export const ORDER_SOURCE_LABELS: Record<OrderSource, string> = {
  application: "Application",
  pos: "POS Orders",
  call: "Call",
};

export const ORDER_SOURCE_COUNTS: Record<OrderSource, number> = {
  application: 44,
  pos: 16,
  call: 8,
};

export const ORDER_SOURCE_SUMMARIES: Record<OrderSource, OrdersSummary> = {
  application: {
    revenue: 7074.4,
    totalOrders: 43,
    pending: 30,
    delivered: 6,
  },
  pos: {
    revenue: 8297.4,
    totalOrders: 16,
    pending: 2,
    delivered: 2,
  },
  call: {
    revenue: 3120.0,
    totalOrders: 8,
    pending: 3,
    delivered: 4,
  },
};

export const DRIVERS: Driver[] = [
  { id: "d1", name: "Omnia" },
  { id: "d2", name: "Karim" },
  { id: "d3", name: "Hassan" },
  { id: "d4", name: "Mariam" },
  { id: "d5", name: "Tarek" },
];

export const DELIVERY_ZONES: DeliveryZone[] = [
  { id: "z1", name: "Kafr Abdo", deliveryFee: 40, minOrder: 250 },
  { id: "z2", name: "Mohandiseen", deliveryFee: 50, minOrder: 300 },
  { id: "z3", name: "Maadi", deliveryFee: 60, minOrder: 320 },
  { id: "z4", name: "Zamalek", deliveryFee: 70, minOrder: 350 },
];

/** Phone numbers that resolve to an existing customer during a call order. */
export const CUSTOMER_DIRECTORY: Record<string, CustomerLookup> = {
  "01288716491": {
    name: "Omnia Maher Galal",
    phone: "01288716491",
    lastAddress: "Villa 4, Bastour, Bab Sharki And Wabour El Miyah, Alexandria",
    tier: "BRONZE (STANDARD)",
  },
};

export const PRODUCT_OPTIONS: ProductOption[] = [
  {
    id: 1,
    name: "Almond Croissant",
    unitPrice: 280,
    category: "Bakery",
    customizable: true,
    extras: [
      { id: 101, name: "Chocolate", price: 85.2 },
      { id: 102, name: "Lotus", price: 85.2 },
      { id: 103, name: "Pistachio", price: 95.0 },
      { id: 104, name: "Caramel", price: 90.5 },
      { id: 105, name: "White Chocolate", price: 92.3 },
    ],
  },
  {
    id: 2,
    name: "Middle Eastern Beef Sandwich",
    unitPrice: 280,
    category: "Sandwiches",
  },
  {
    id: 3,
    name: "Kunafa Trimsiu",
    unitPrice: 280,
    category: "Bakery",
    customizable: true,
    extras: [
      { id: 301, name: "Extra Nuts", price: 30.0 },
      { id: 302, name: "Chocolate Drizzle", price: 25.0 },
    ],
  },
  { id: 4, name: "Biryani Masala", unitPrice: 150, category: "Meals" },
  {
    id: 5,
    name: "Cappuccino",
    unitPrice: 120,
    category: "Coffee",
    customizable: true,
    variantGroups: [
      {
        id: 51,
        name: "Roast Level",
        required: true,
        options: [
          { id: 511, name: "Light", price: 40 },
          { id: 512, name: "Medium", price: 50 },
          { id: 513, name: "Dark", price: 60 },
        ],
      },
      {
        id: 52,
        name: "Grind Type",
        required: true,
        options: [
          { id: 521, name: "Whole Bean", price: 40 },
          { id: 522, name: "Espresso", price: 60 },
          { id: 523, name: "Filter", price: 60 },
        ],
      },
    ],
  },
  { id: 6, name: "Stuffed Grape Leaves", unitPrice: 100, category: "Meals" },
  { id: 7, name: "Falafel Wrap", unitPrice: 90, category: "Sandwiches" },
  { id: 8, name: "Hummus with Pita", unitPrice: 70, category: "Meals" },
  {
    id: 9,
    name: "Baklava Delight",
    unitPrice: 60,
    category: "Bakery",
    customizable: true,
    extras: [
      { id: 901, name: "Extra Honey", price: 15.0 },
      { id: 902, name: "Ice Cream Scoop", price: 35.0 },
    ],
  },
];

const repeatedItems = [
  {
    id: 1,
    name: "Avocado Ranch",
    quantity: 9,
    unitPrice: 140,
    note: "Remove Mushroom",
  },
  {
    id: 2,
    name: "Avocado Ranch",
    quantity: 9,
    unitPrice: 140,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-214067",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    customerEmail: "layla@example.com",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Preparing",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash",
    paymentState: "Waiting for payment",
    items: repeatedItems,
    driver: "Omnia",
  },
  {
    id: "ORD-214068",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    customerEmail: "layla@example.com",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Pending",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 3, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 4, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "ORD-214069",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "On The Way",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash 90 + Visa 190",
    paymentState: "Waiting for payment",
    items: repeatedItems,
  },
  {
    id: "ORD-214070",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Cancelled",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash",
    paymentState: "None",
    items: [
      { id: 5, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 6, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "ORD-214071",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Delivered",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 7, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 8, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "POS-688377",
    customerName: "Walk-in Customer",
    customerPhone: "+20 122 555 7890",
    address: "Patria Branch",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 1940,
    subtotal: 1940,
    discount: 0,
    deliveryFee: 0,
    status: "Preparing",
    category: "Meals",
    source: "pos",
    paymentMethod: "Cash",
    paymentState: "Waiting for payment",
    items: [
      { id: 9, name: "Middle Eastern Roast Beef", quantity: 2, unitPrice: 120 },
      { id: 10, name: "Green Ranch Sandwich", quantity: 2, unitPrice: 320 },
      { id: 11, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 12, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 13, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 14, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "POS-688378",
    customerName: "Youssef",
    customerPhone: "+20 122 555 7890",
    address: "Patria Branch",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 2510,
    subtotal: 2510,
    discount: 0,
    deliveryFee: 0,
    status: "Pending",
    category: "Meals",
    source: "pos",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 15, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 16, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "CALL-512001",
    customerName: "Omnia Maher Galal",
    customerPhone: "01288716491",
    address: "Villa 4, Bastour, Bab Sharki And Wabour El Miyah, Alexandria",
    zone: "Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 310,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 40,
    status: "Preparing",
    category: "Coffee",
    source: "call",
    paymentMethod: "Cash 90 + Visa 190",
    paymentState: "Waiting for payment",
    items: [
      { id: 17, name: "Cappuccino", quantity: 2, unitPrice: 170.4 },
      { id: 18, name: "Almond Croissant", quantity: 2, unitPrice: 170.4 },
    ],
    driver: "Karim",
  },
  {
    id: "CALL-512002",
    customerName: "Ahmed El-Sayed",
    customerPhone: "+20 122 555 7890",
    address: "Abo Al Nwateer, Alexandria",
    zone: "Maadi",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 460,
    subtotal: 400,
    discount: 0,
    deliveryFee: 60,
    status: "Delivered",
    category: "Meals",
    source: "call",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 19, name: "Biryani Masala", quantity: 2, unitPrice: 150 },
      { id: 20, name: "Hummus with Pita", quantity: 1, unitPrice: 70 },
    ],
  },
];
