import type {
  Order,
  OrderCategory,
  OrderSource,
  OrdersSummary,
  OrderStatus,
  ProductOption,
} from "./types";

export const ORDER_STATUS_OPTIONS: OrderStatus[] = [
  "Pending",
  "Confirmed",
  "Preparing",
  "On The Way",
  "Delivered",
  "Cancelled",
];

export const ORDER_CATEGORY_OPTIONS: OrderCategory[] = [
  "All Categories",
  "Sandwiches",
  "Coffee",
  "Bakery",
  "Meals",
];

export const ORDER_SOURCE_LABELS: Record<OrderSource, string> = {
  application: "Application",
  pos: "POS Orders",
};

export const ORDER_SOURCE_SUMMARIES: Record<OrderSource, OrdersSummary> = {
  application: {
    revenue: 7074.4,
    totalOrders: 43,
    pending: 30,
    delivered: 6,
  },
  pos: {
    revenue: 8297.4,
    totalOrders: 16,
    pending: 2,
    delivered: 2,
  },
};

export const PRODUCT_OPTIONS: ProductOption[] = [
  {
    id: 1,
    name: "Middle Eastern Roast Beef",
    unitPrice: 120,
    category: "Sandwiches",
  },
  {
    id: 2,
    name: "Green Ranch Sandwich",
    unitPrice: 120,
    category: "Sandwiches",
  },
  {
    id: 3,
    name: "Avocado Ranch",
    unitPrice: 140,
    category: "Sandwiches",
  },
  { id: 4, name: "Almond Croissant", unitPrice: 95, category: "Bakery" },
  { id: 5, name: "Amber Sobia", unitPrice: 80, category: "Coffee" },
];

const repeatedItems = [
  {
    id: 1,
    name: "Avocado Ranch",
    quantity: 9,
    unitPrice: 140,
    note: "Remove Mushroom",
  },
  {
    id: 2,
    name: "Avocado Ranch",
    quantity: 9,
    unitPrice: 140,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-214067",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    customerEmail: "layla@example.com",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Preparing",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash",
    paymentState: "Waiting for payment",
    items: repeatedItems,
  },
  {
    id: "ORD-214068",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    customerEmail: "layla@example.com",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Pending",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 3, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 4, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "ORD-214069",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "On The Way",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash 90 + Visa 190",
    paymentState: "Waiting for payment",
    items: repeatedItems,
  },
  {
    id: "ORD-214070",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Cancelled",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Cash",
    paymentState: "None",
    items: [
      { id: 5, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 6, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "ORD-214071",
    customerName: "Layla Ibrahim",
    customerPhone: "+20 122 555 7890",
    address: "12 Sea View St, Kafr Abdo",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 280,
    subtotal: 250.25,
    discount: 0,
    deliveryFee: 27,
    status: "Delivered",
    category: "Sandwiches",
    source: "application",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 7, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 8, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "POS-688377",
    customerName: "Walk-in Customer",
    customerPhone: "+20 122 555 7890",
    address: "Patria Branch",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 1940,
    subtotal: 1940,
    discount: 0,
    deliveryFee: 0,
    status: "Preparing",
    category: "Meals",
    source: "pos",
    paymentMethod: "Cash",
    paymentState: "Waiting for payment",
    items: [
      { id: 9, name: "Middle Eastern Roast Beef", quantity: 2, unitPrice: 120 },
      { id: 10, name: "Green Ranch Sandwich", quantity: 2, unitPrice: 320 },
      { id: 11, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 12, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 13, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 14, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
  {
    id: "POS-688378",
    customerName: "Youssef",
    customerPhone: "+20 122 555 7890",
    address: "Patria Branch",
    date: "3/31/2026",
    time: "2:37:57 PM",
    total: 2510,
    subtotal: 2510,
    discount: 0,
    deliveryFee: 0,
    status: "Pending",
    category: "Meals",
    source: "pos",
    paymentMethod: "Online Payment",
    paymentState: "Paid",
    items: [
      { id: 15, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
      { id: 16, name: "Avocado Ranch", quantity: 9, unitPrice: 140 },
    ],
  },
];
