import type { Coupon } from "./types";

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 1,
    code: "WELCOME20",
    discountType: "fixed",
    discountValue: 50,
    minOrderAmount: 0,
    usageLimit: 0,
    usedCount: 2,
    startDate: "2026-04-07",
    endDate: "2026-04-14",
    isActive: true,
  },
  {
    id: 2,
    code: "RMDKAREEM",
    discountType: "percentage",
    discountValue: 20,
    minOrderAmount: 85,
    usageLimit: 20,
    usedCount: 2,
    startDate: "2026-04-07",
    endDate: "2026-04-14",
    isActive: false,
  },
  {
    id: 3,
    code: "FIRST30",
    discountType: "percentage",
    discountValue: 30,
    minOrderAmount: 150,
    usageLimit: 0,
    usedCount: 3,
    startDate: "2026-04-07",
    endDate: "2026-04-14",
    isActive: true,
  },
  {
    id: 4,
    code: "EIDMUBARAK",
    discountType: "percentage",
    discountValue: 15,
    minOrderAmount: 200,
    usageLimit: 50,
    usedCount: 0,
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    isActive: false,
  },
  {
    id: 5,
    code: "NEWUSER10",
    discountType: "fixed",
    discountValue: 30,
    minOrderAmount: 0,
    usageLimit: 100,
    usedCount: 0,
    startDate: "2026-05-01",
    endDate: "2026-12-31",
    isActive: false,
  },
];
