import type { Customer } from "./types";

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: "Layla Ibrahim",
    role: "subscriber",
    email: "staff@erb.com",
    phone: "012456789",
    tier: "Gold",
    loyaltyPoints: 12,
    lifetimeValue: 1200,
    segment: "STAFF",
  },
  {
    id: 2,
    name: "Ahmed El-Sayed",
    role: "user",
    email: "Ahmed@gmail.com",
    phone: "0123456789",
    tier: "Silver",
    loyaltyPoints: 8,
    lifetimeValue: 800.45,
    segment: "STAFF",
  },
  {
    id: 3,
    name: "Omar Khaled",
    role: "admin",
    email: "admin@erb.com",
    phone: "0123456789",
    tier: "Bronze",
    loyaltyPoints: 0,
    lifetimeValue: 150,
    segment: "STAFF",
  },
  {
    id: 4,
    name: "Youssef Nabil",
    role: "manager",
    email: "manager@erb.com",
    phone: "0123456789",
    tier: "Bronze",
    loyaltyPoints: 0,
    lifetimeValue: 0,
    segment: "STAFF",
  },
  {
    id: 5,
    name: "Omnia Maher",
    role: "user",
    email: "ynabil@gmail.com",
    phone: "0123456789",
    tier: "Bronze",
    loyaltyPoints: 0,
    lifetimeValue: 0,
    segment: "STAFF",
    createdBy: "Layla Ibrahim",
  },
];

export const CUSTOMER_OVERVIEW = {
  totalCustomers: 7,
  activeCustomersToday: 5,
  activeCoupons: 2,
};
