import type { Customer } from "./types";

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: "Layla Ibrahim",
    role: "STAFF",
    nameSubtitle: "Layla Ibrahim",
    isSubscriber: true,
    email: "staff@erb.com",
    phone: "012456789",
    date: "Mar 15, 2026",
    tier: "Gold",
    tierLabel: "GOLD (WHOLESALE VIP)",
    points: 12,
    ltv: 1200,
    ltvLabel: "STAFF",
  },
  {
    id: 2,
    name: "Ahmed El-Sayed",
    role: "USER",
    nameSubtitle: "USER",
    email: "ahmed@gmail.com",
    phone: "0123456789",
    date: "Mar 13, 2026",
    tier: "Silver",
    tierLabel: "SILVER (PRO)",
    points: 8,
    ltv: 800.45,
    ltvLabel: "STAFF",
  },
  {
    id: 3,
    name: "Omar Khaled",
    role: "ADMIN",
    nameSubtitle: "ADMIN",
    email: "admin@erb.com",
    phone: "0123456789",
    date: "Mar 11, 2026",
    tier: "Bronze",
    tierLabel: "BRONZE (STANDARD)",
    points: 0,
    ltv: 150,
    ltvLabel: "STAFF",
  },
  {
    id: 4,
    name: "Youssef Nabil",
    role: "MANAGER",
    nameSubtitle: "MANAGER",
    email: "manager@erb.com",
    phone: "0123456789",
    date: "Mar 08, 2026",
    tier: "Bronze",
    tierLabel: "BRONZE (STANDARD)",
    points: 0,
    ltv: 0,
    ltvLabel: "STAFF",
  },
  {
    id: 5,
    name: "Omnia Maher",
    role: "USER",
    nameSubtitle: "Layla Ibrahim",
    email: "ynabil@gmail.com",
    phone: "0123456789",
    date: "Mar 06, 2026",
    tier: "Bronze",
    tierLabel: "BRONZE (STANDARD)",
    points: 0,
    ltv: 0,
    ltvLabel: "STAFF",
  },
];
