import type { AppNotification } from "./types";

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 1,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Garlic Paste in Main Inventory — only 3 jars remaining",
    time: "3h ago",
    read: false,
    resolved: false,
  },
  {
    id: 2,
    category: "orders",
    title: "New Order Received at Barista",
    description: "Lucas Martin — 2x Flat White, 1x Croissant",
    time: "3h ago",
    read: false,
    resolved: false,
  },
  {
    id: 3,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Oat Milk in Barista Station — only 2 cartons remaining",
    time: "3h ago",
    read: false,
    resolved: false,
  },
  {
    id: 4,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Espresso Beans in Main Inventory — only 4 kg remaining",
    time: "5h ago",
    read: false,
    resolved: false,
  },
  {
    id: 5,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Sourdough Loaf in Bakery — only 5 units remaining",
    time: "6h ago",
    read: true,
    resolved: false,
  },
  {
    id: 6,
    category: "orders",
    title: "New Order Received at Bakery",
    description: "Lucas Martin — 2x Flat White, 1x Croissant",
    time: "7h ago",
    read: false,
    resolved: false,
  },
  {
    id: 7,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Caramel Syrup in Barista Station — only 1 bottle remaining",
    time: "8h ago",
    read: true,
    resolved: false,
  },
  {
    id: 8,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Whole Milk in Main Inventory — only 6 cartons remaining",
    time: "9h ago",
    read: false,
    resolved: false,
  },
  {
    id: 9,
    category: "stock",
    title: "Critical Stock Alert",
    description: "Butter in Bakery — only 2 blocks remaining",
    time: "10h ago",
    read: false,
    resolved: false,
  },
  {
    id: 10,
    category: "system",
    title: "Daily Backup Completed",
    description: "All administrative data was synced successfully",
    time: "12h ago",
    read: true,
    resolved: false,
  },
  {
    id: 11,
    category: "system",
    title: "New Device Signed In",
    description: "Admin account accessed from a new browser session",
    time: "1d ago",
    read: false,
    resolved: false,
  },
];
