import type { Kitchen, KitchenOrder } from "./types";

export const KITCHENS: Kitchen[] = [
  {
    id: "main-kitchen",
    name: "Main Kitchen",
    description: "Operational kitchen station",
    status: "active",
    color: "#8F6900",
    icon: "main",
    activeOrders: 12,
    requests: 3,
    detailActiveOrders: 4,
    lowStock: 1,
  },
  {
    id: "pastry",
    name: "Pastry",
    description: "Operational kitchen station",
    status: "busy",
    color: "#A856F7",
    icon: "pastry",
    activeOrders: 18,
    requests: 5,
    detailActiveOrders: 5,
    lowStock: 2,
  },
  {
    id: "barista",
    name: "Barista",
    description: "Operational kitchen station",
    status: "active",
    color: "#F9A825",
    icon: "barista",
    activeOrders: 8,
    requests: 0,
    detailActiveOrders: 2,
    lowStock: 3,
  },
];

export const KITCHEN_ORDERS: Record<string, KitchenOrder[]> = {
  "main-kitchen": [
    {
      id: "mk-1",
      orderNumber: "#ORD-101",
      receivedAt: "Received 6 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123451111",
      items: ["1x Chicken Bowl", "1x Beef Burger"],
      type: "takeaway",
      status: "preparing",
    },
    {
      id: "mk-2",
      orderNumber: "#ORD-102",
      receivedAt: "Received 12 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123452222",
      items: ["1x Caesar Salad", "2x Fries"],
      type: "dine-in",
      status: "delivered",
    },
  ],
  pastry: [
    {
      id: "p-1",
      orderNumber: "#ORD-150",
      receivedAt: "Received 4 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123453333",
      items: ["2x Croissant", "1x Cinnamon Roll"],
      type: "takeaway",
      status: "preparing",
    },
    {
      id: "p-2",
      orderNumber: "#ORD-151",
      receivedAt: "Received 15 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123454444",
      items: ["1x Chocolate Tart", "1x Eclair"],
      type: "dine-in",
      status: "rejected",
    },
  ],
  barista: [
    {
      id: "b-1",
      orderNumber: "#ORD-2001",
      receivedAt: "Received at 5:26 AM",
      customerType: "Walk-in Customer",
      customerPhone: "0123456789",
      items: ["1x Flat White", "2x Almond Latte"],
      type: "takeaway",
      status: "delivered",
    },
    {
      id: "b-2",
      orderNumber: "#ORD-2001",
      receivedAt: "Received 8 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123456789",
      items: ["1x Cold Brew", "1x Vanilla Iced"],
      type: "dine-in",
      status: "preparing",
    },
    {
      id: "b-3",
      orderNumber: "#ORD-2001",
      receivedAt: "Received 20 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123456789",
      items: ["1x Flat White", "2x Almond Latte"],
      type: "takeaway",
      status: "rejected",
    },
    {
      id: "b-4",
      orderNumber: "#ORD-2001",
      receivedAt: "Received 22 mins ago",
      customerType: "Walk-in Customer",
      customerPhone: "0123456789",
      items: ["1x Flat White", "2x Almond Latte"],
      type: "takeaway",
      status: "delivered",
    },
  ],
};
