import type {
  InventoryMetric,
  KitchenInventoryDetails,
  StockLevelIndicator,
} from "./types";

export const INVENTORY_METRICS: InventoryMetric[] = [
  {
    id: "total-items",
    title: "Total Items",
    value: 24,
    cardColor: "#F5F0EA",
    iconColor: "#8F6900",
    valueColor: "#28293D",
    icon: "package",
  },
  {
    id: "critical-stock",
    title: "Critical Stock",
    value: 7,
    cardColor: "#FFF0F0",
    iconColor: "#C90000",
    valueColor: "#C90000",
    icon: "alert",
  },
  {
    id: "total-products",
    title: "Total Products",
    value: 4,
    cardColor: "#FE9A001A",
    iconColor: "#C7861E",
    valueColor: "#C7861E",
    icon: "triangle",
  },
  {
    id: "excess-stock",
    title: "Excess Stock",
    value: 3,
    cardColor: "#E2F4ED",
    iconColor: "#059B5A",
    valueColor: "#059B5A",
    icon: "arrow-up",
  },
];

export const STOCK_LEVELS: StockLevelIndicator[] = [
  {
    status: "excess",
    label: "Excess (≥50)",
    bgColor: "#E2F4ED",
    textColor: "#059B5A",
  },
  {
    status: "normal",
    label: "Normal",
    bgColor: "#F5F0EA",
    textColor: "#8F6900",
  },
  {
    status: "low",
    label: "Low (≤15)",
    bgColor: "#FE9A001A",
    textColor: "#C7861E",
  },
  {
    status: "critical",
    label: "Critical (≤5)",
    bgColor: "#FFF0F0",
    textColor: "#C90000",
  },
];

export const KITCHEN_INVENTORY: KitchenInventoryDetails[] = [
  {
    id: "main-kitchen",
    name: "Main Kitchen",
    icon: "main",
    accentColor: "#8F6900",
    totalTrackedItems: 6,
    status: "active",
    subtitle: "6 items tracked",
    distribution: {
      critical: 1,
      low: 1,
      normal: 0,
      excess: 4,
    },
    items: [
      {
        id: "mk-espresso-beans",
        name: "Espresso Beans",
        quantity: 1,
        unit: "kg",
        status: "critical",
      },
      {
        id: "mk-milk",
        name: "Milk",
        quantity: 12,
        unit: "bottles",
        status: "normal",
      },
      {
        id: "mk-butter",
        name: "Butter",
        quantity: 2,
        unit: "kg",
        status: "low",
      },
      {
        id: "mk-flour",
        name: "Flour",
        quantity: 40,
        unit: "kg",
        status: "excess",
      },
      {
        id: "mk-tomato-sauce",
        name: "Tomato Sauce",
        quantity: 20,
        unit: "bottles",
        status: "excess",
      },
      {
        id: "mk-rice",
        name: "Rice",
        quantity: 60,
        unit: "kg",
        status: "excess",
      },
    ],
  },
  {
    id: "barista",
    name: "Barista",
    icon: "barista",
    accentColor: "#FE9A00",
    totalTrackedItems: 7,
    status: "active",
    subtitle: "7 items . Inventory management",
    distribution: {
      critical: 4,
      low: 1,
      normal: 1,
      excess: 1,
    },
    items: [
      {
        id: "b-espresso-beans",
        name: "Espresso Beans",
        quantity: 3,
        unit: "kg",
        status: "critical",
      },
      {
        id: "b-almond-milk",
        name: "Almond Milk",
        quantity: 6,
        unit: "bottles",
        status: "low",
      },
      {
        id: "b-caramel-sauce",
        name: "Caramel Sauce",
        quantity: 3,
        unit: "bottles",
        status: "critical",
      },
      {
        id: "b-water-bottles",
        name: "Water Bottles",
        quantity: 12,
        unit: "bottles",
        status: "critical",
      },
      {
        id: "b-oat-milk",
        name: "Oat Milk",
        quantity: 60,
        unit: "bottles",
        status: "excess",
      },
      {
        id: "b-coffee-cups",
        name: "Coffee Cups (L)",
        quantity: 250,
        unit: "Units",
        status: "normal",
      },
      {
        id: "b-vanilla-syrup",
        name: "Vanilla Syrup",
        quantity: 3,
        unit: "bottles",
        status: "critical",
      },
    ],
  },
  {
    id: "pastry",
    name: "Pastry",
    icon: "pastry",
    accentColor: "#A855F7",
    totalTrackedItems: 6,
    status: "active",
    subtitle: "6 items tracked",
    distribution: {
      critical: 4,
      low: 0,
      normal: 1,
      excess: 1,
    },
    items: [
      {
        id: "p-butter",
        name: "Butter",
        quantity: 1,
        unit: "kg",
        status: "critical",
      },
      {
        id: "p-flour",
        name: "Flour",
        quantity: 2,
        unit: "kg",
        status: "critical",
      },
      {
        id: "p-vanilla-extract",
        name: "Vanilla Extract",
        quantity: 1,
        unit: "bottle",
        status: "critical",
      },
      {
        id: "p-cocoa-powder",
        name: "Cocoa Powder",
        quantity: 1,
        unit: "kg",
        status: "critical",
      },
      {
        id: "p-sugar",
        name: "Sugar",
        quantity: 30,
        unit: "kg",
        status: "excess",
      },
      {
        id: "p-egg-cartons",
        name: "Egg Cartons",
        quantity: 12,
        unit: "cartons",
        status: "normal",
      },
    ],
  },
];
