import type { InventoryItem } from "./types";

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 1,
    name: "Kunafa Tiramsu",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=80&q=80",
    category: "Bakery",
    currentQuantity: 0,
    minimumQuantity: 10,
    status: "Out Of Stock",
    salesRatePerDay: null,
    expectedExpiryDate: null,
    daysRemaining: null,
    urgencyLevel: "Sufficient stock",
  },
  {
    id: 2,
    name: "Tomatoes",
    image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=80&q=80",
    category: "Raw Ingredient",
    currentQuantity: 0,
    minimumQuantity: 10,
    status: "Out Of Stock",
    salesRatePerDay: 0.5,
    expectedExpiryDate: "2026-04-22",
    daysRemaining: 5,
    urgencyLevel: "Critical",
  },
  {
    id: 3,
    name: "Amber Sobila",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=80&q=80",
    category: "Barista",
    currentQuantity: 7,
    minimumQuantity: 10,
    status: "Low Stock",
    salesRatePerDay: 0.2,
    expectedExpiryDate: null,
    daysRemaining: 45,
    urgencyLevel: "Good",
  },
  {
    id: 4,
    name: "Artisanal Sourdough",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=80&q=80",
    category: "Bakery",
    currentQuantity: 0,
    minimumQuantity: 5,
    status: "Out Of Stock",
    salesRatePerDay: 1.33,
    expectedExpiryDate: "2026-04-22",
    daysRemaining: 5,
    urgencyLevel: "Critical",
  },
  {
    id: 5,
    name: "Eish el Saraya",
    image: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=80&q=80",
    category: "Bakery",
    currentQuantity: 0,
    minimumQuantity: 8,
    status: "Out Of Stock",
    salesRatePerDay: 0.1,
    expectedExpiryDate: "2026-04-22",
    daysRemaining: 5,
    urgencyLevel: "Critical",
  },
  {
    id: 6,
    name: "Middle Eastern Roast Beef",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=80&q=80",
    category: "Raw Ingredient",
    currentQuantity: 0,
    minimumQuantity: 5,
    status: "Out Of Stock",
    salesRatePerDay: 0.07,
    expectedExpiryDate: "2026-04-22",
    daysRemaining: 5,
    urgencyLevel: "Critical",
  },
  {
    id: 7,
    name: "Brazilian Coffee",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=80&q=80",
    category: "Barista",
    currentQuantity: 7,
    minimumQuantity: 3,
    status: "Available",
    salesRatePerDay: 0.2,
    expectedExpiryDate: null,
    daysRemaining: 45,
    urgencyLevel: "Good",
  },
];

export const INVENTORY_VALUE = 12000;
